tokenizer:
  model_name: gpt2-large
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True

reward_fn:
  id: "pictionary_reward"

datapool:
  id: "pictionary_datapool"

env:
  n_envs: 1    # TODO: put this back to 10 envs
  args:
    max_prompt_length: 128
    max_episode_length: 24
    terminate_on_eos: True

alg:
  id: ppo
  args: 
    n_steps: 128                # was 128; rollout buffer is n_steps * n_envs
    batch_size: 16              # was 64; inner loop: n_epochs times, sample this size from the buffer
    verbose: 1
    learning_rate: 0.000001
    n_epochs: 5
    
  kl_div:
    coeff: 0.2
    target_kl: 0.5
 
  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: gpt2-large
      apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        top_k: 100
        min_length: 2
        max_new_tokens: 24
      
train_evaluation:
  eval_batch_size: 16   # was 32
  n_iters: 50           # Total actual "epochs" (outer loop) - each iter calls alg.learn() -> algo.train() once per iter
  eval_every: 5         # eval_every 5 *iters* where each iter has five collections of rollouts (n_epochs)
  save_every: 10
  metrics:
    - id: pictionary_metric
    - id: causal_perplexity
      args:
        tokenizer_id: gpt2-large
        stride: 128
        model_type: causal
  generation_kwargs:
    do_sample: True
    top_k: 100
    min_length: 2
    max_new_tokens: 24
